server:
  port: 8080
#  servlet:
#    encoding:
#      force-response: true
#    session:
#      timeout: PT60S
#    context-path: ''

spring:
  datasource:
    username: root
    password: ahu=2018
    url: jdbc:mysql://60.205.124.179:3306/red_carp?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 60.205.124.179
    port: 6379
    password: ahu=20181
#  aop:
#    proxy-target-class: true
#  session:
#    store-type: redis
#    redis:
#      flush-mode: on_save
#      namespace: wuzhong:session
#  jackson:
#    date-format: yyyy-mm-dd HH:mm:ss

mybatis:
  mapper-locations: classpath:measure/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
